spring:
  application:
    name: bookstore
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bookstore
    username: jokindy
    password: iamroot
  liquibase:
    change-log: db/changelog/db-changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8484/realms/BookStore
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8484/realms/BookStore

jwt:
  auth:
    converter:
      resource-id: login-app
      principal-attribute: principal_username